version: '2'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis-abr

  postgres:
    image: postgres
    ports:
      # TODO - fix port to 5432
      - "5433:5432"
    container_name: postgres-abr
