version: '2'

services:

  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis-abr

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-abr
    volumes:
      - abr-postgres:/var/lib/postgresql/data


volumes:
  abr-postgres:
