version: '2.1'

services:

  abr:
    build: .
    image: flackdl/abr
    ports:
      - "80:80"
    container_name: abr
    env_file: .env

  redis:
    image: redis
    expose:
      - "6379"
    container_name: redis

  postgres:
    image: postgres:12
    expose:
      - "5432"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
    volumes:
      - abr-postgres:/var/lib/postgresql/data
    env_file: .env


volumes:
  abr-postgres:
