# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180328_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEstimatePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_id', models.IntegerField()),
                ('part_id', models.IntegerField()),
                ('part_sku', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderpart',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderPart',
        ),
    ]
