# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180328_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderestimatepart',
            name='part_sku',
        ),
    ]
