# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_orderestimatepart_part_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderEstimatePart',
            new_name='OrderPart',
        ),
    ]
