# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180401_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('order_id', 'vendor')]),
        ),
    ]
