# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderpart_part_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpart',
            name='part_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
