# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderpart_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='part_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderpart',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
    ]
