# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180416_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpart',
            name='part_description',
            field=models.TextField(blank=True),
        ),
    ]
