# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180416_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpart',
            name='part_name',
        ),
    ]
