# Generated by Django 2.2.7 on 2019-11-24 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_servicecategory_servicecategoryprefix_serviceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceItem',
        ),
    ]
