# Generated by Django 2.2.7 on 2019-11-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191124_0438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ServiceCategoryPrefix',
            new_name='CategoryPrefix',
        ),
    ]
