# Generated by Django 2.2.7 on 2019-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_categoryassessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryassessment',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
