# Generated by Django 2.2.7 on 2019-11-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191125_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryprefix',
            options={'verbose_name_plural': 'category prefixes'},
        ),
        migrations.AlterField(
            model_name='categoryassessment',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='categoryassessment',
            unique_together=set(),
        ),
    ]
