# Generated by Django 2.2.7 on 2019-11-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191126_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprefix',
            name='back',
            field=models.BooleanField(default=False, help_text='Rear of bike'),
        ),
        migrations.AddField(
            model_name='categoryprefix',
            name='front',
            field=models.BooleanField(default=False, help_text='Front of bike'),
        ),
        migrations.AlterField(
            model_name='categoryassessment',
            name='back',
            field=models.BooleanField(default=False, help_text='Rear of bike'),
        ),
    ]
