# Generated by Django 2.2.7 on 2019-11-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20191126_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='front_and_back',
            new_name='front_and_rear',
        ),
        migrations.RenameField(
            model_name='categoryassessment',
            old_name='back',
            new_name='rear',
        ),
        migrations.RenameField(
            model_name='categoryprefix',
            old_name='back',
            new_name='rear',
        ),
    ]
