# Generated by Django 2.2.7 on 2019-11-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20191126_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='front_and_rear',
        ),
        migrations.RemoveField(
            model_name='categoryprefix',
            name='front',
        ),
        migrations.RemoveField(
            model_name='categoryprefix',
            name='rear',
        ),
        migrations.DeleteModel(
            name='CategoryAssessment',
        ),
    ]
