# Generated by Django 2.2.7 on 2019-11-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_categorychild'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='service_only',
            field=models.BooleanField(default=False),
        ),
    ]
