# Generated by Django 2.2.7 on 2019-11-28 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_category_service_only'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryChild',
        ),
    ]
