# Generated by Django 2.2.7 on 2019-12-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_categorychild'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryprefix',
            name='service_only',
            field=models.BooleanField(default=False),
        ),
    ]
