# Generated by Django 2.2.7 on 2019-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_categoryprefix_service_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryprefix',
            name='service_only',
        ),
        migrations.AddField(
            model_name='categoryprefix',
            name='type',
            field=models.CharField(choices=[('Inventory', 'inventory'), ('Service', 'service')], default='inventory', max_length=20),
            preserve_default=False,
        ),
    ]
