# Generated by Django 2.2.7 on 2019-12-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20191208_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryprefix',
            name='type',
            field=models.CharField(choices=[('inventory', 'Inventory'), ('service', 'Service')], max_length=20),
        ),
    ]
