# Generated by Django 2.2.7 on 2020-01-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20191230_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_assessment',
            field=models.BooleanField(default=True),
        ),
    ]
