# Generated by Django 3.0.2 on 2020-01-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_category_show_in_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='service_only',
        ),
    ]
