# Generated by Django 3.0.2 on 2020-01-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_category_service_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='show_in_assessment',
        ),
    ]
